Repository Mango-Jelly/Backend, pull requests merged in 2024-01, with the labels that each got.

#3 Feat/#2
  src/main/java/com/mangojelly/backend/domain/Guest/Guest.java
  src/main/java/com/mangojelly/backend/domain/Guest/GuestRepository.java
  src/main/java/com/mangojelly/backend/domain/Member/Member.java
  src/main/java/com/mangojelly/backend/domain/Member/MemberRepository.java
  src/main/java/com/mangojelly/backend/domain/Movie/Movie.java
  src/main/java/com/mangojelly/backend/domain/Movie/MovieRepository.java
  src/main/java/com/mangojelly/backend/domain/Role/Role.java
  src/main/java/com/mangojelly/backend/domain/Role/RoleRepository.java
  src/main/java/com/mangojelly/backend/domain/Room/Room.java
  src/main/java/com/mangojelly/backend/domain/Room/RoomRepository.java
  src/main/java/com/mangojelly/backend/domain/Scene/Scene.java
  src/main/java/com/mangojelly/backend/domain/Scene/SceneRepository.java
  src/main/java/com/mangojelly/backend/domain/SceneMovie/SceneMovie.java
  src/main/java/com/mangojelly/backend/domain/SceneMovie/SceneMovieRepository.java
  src/main/java/com/mangojelly/backend/domain/Script/Script.java
  src/main/java/com/mangojelly/backend/domain/Script/ScriptRepository.java
  src/main/java/com/mangojelly/backend/global/common/BaseEntity.java
  src/main/java/com/mangojelly/backend/global/error/ErrorCode.java
  src/main/java/com/mangojelly/backend/global/error/ErrorResponse.java
  src/main/java/com/mangojelly/backend/global/error/GlobalExceptionHandler.java
  src/main/java/com/mangojelly/backend/global/error/exception/BusinessException.java
  src/main/java/com/mangojelly/backend/global/response/api/ApiBaseResponse.java
  src/main/java/com/mangojelly/backend/global/response/api/ResponseCode.java
Labels: 기능

#8 Feat(#6):Swagger 적용
  build.gradle
  src/main/java/com/mangojelly/backend/applicatoin/controller/HelloController.java
  src/main/java/com/mangojelly/backend/global/config/SwaggerConfig.java
  src/main/java/com/mangojelly/backend/global/response/api/ApiResponse.java
  src/main/resources/application.yml
Labels: 기능

#10 Fix(#9) 패키지명 대문자
  src/main/java/com/mangojelly/backend/domain/guest/Guest.java
  src/main/java/com/mangojelly/backend/domain/guest/GuestRepository.java
  src/main/java/com/mangojelly/backend/domain/member/Member.java
  src/main/java/com/mangojelly/backend/domain/member/MemberRepository.java
  src/main/java/com/mangojelly/backend/domain/movie/Movie.java
  src/main/java/com/mangojelly/backend/domain/movie/MovieRepository.java
  src/main/java/com/mangojelly/backend/domain/role/Role.java
  src/main/java/com/mangojelly/backend/domain/role/RoleRepository.java
  src/main/java/com/mangojelly/backend/domain/room/Room.java
  src/main/java/com/mangojelly/backend/domain/room/RoomRepository.java
  src/main/java/com/mangojelly/backend/domain/scene/Scene.java
  src/main/java/com/mangojelly/backend/domain/scene/SceneRepository.java
  src/main/java/com/mangojelly/backend/domain/sceneMovie/SceneMovie.java
  src/main/java/com/mangojelly/backend/domain/sceneMovie/SceneMovieRepository.java
  src/main/java/com/mangojelly/backend/domain/script/Script.java
  src/main/java/com/mangojelly/backend/domain/script/ScriptRepository.java
Labels: 버그

#13 Feat/#7 채팅
  build.gradle
  src/main/java/com/mangojelly/backend/domain/socket/Message.java
  src/main/java/com/mangojelly/backend/domain/socket/MessageController.java
  src/main/java/com/mangojelly/backend/domain/socket/WebSocketConfigurer.java
Labels: 기능

#15 Feat/#11
  .gitignore
  build.gradle
  src/main/java/com/mangojelly/backend/applicatoin/controller/MemberController.java
  src/main/java/com/mangojelly/backend/applicatoin/dto/request/LoginRequest.java
  src/main/java/com/mangojelly/backend/applicatoin/dto/request/SignupRequest.java
  src/main/java/com/mangojelly/backend/applicatoin/facade/MemberFacade.java
  src/main/java/com/mangojelly/backend/domain/authToken/AuthToken.java
  src/main/java/com/mangojelly/backend/domain/authToken/AuthTokenMapper.java
  src/main/java/com/mangojelly/backend/domain/authToken/AuthTokenRepository.java
  src/main/java/com/mangojelly/backend/domain/authToken/AuthTokenService.java
  src/main/java/com/mangojelly/backend/domain/member/Member.java
  src/main/java/com/mangojelly/backend/domain/member/MemberCustomService.java
  src/main/java/com/mangojelly/backend/domain/member/MemberMapper.java
  src/main/java/com/mangojelly/backend/domain/member/MemberRepository.java
  src/main/java/com/mangojelly/backend/domain/member/MemberService.java
  src/main/java/com/mangojelly/backend/global/common/Authenticated.java
  src/main/java/com/mangojelly/backend/global/config/SecurityConfig.java
  src/main/java/com/mangojelly/backend/global/error/ErrorCode.java
  src/main/java/com/mangojelly/backend/global/error/GlobalExceptionHandler.java
  src/main/java/com/mangojelly/backend/global/error/exception/BusinessException.java
  src/main/java/com/mangojelly/backend/global/response/api/ResponseCode.java
  src/main/java/com/mangojelly/backend/global/security/annotation/AuthenticatedArgumentResolver.java
  src/main/java/com/mangojelly/backend/global/security/support/AccessDeniedHandler.java
  src/main/java/com/mangojelly/backend/global/security/support/AuthenticationEntryPoint.java
  src/main/java/com/mangojelly/backend/global/security/support/AuthenticationFilter.java
  src/main/java/com/mangojelly/backend/global/security/support/TokenProvider.java
  src/main/java/com/mangojelly/backend/global/security/support/TokenResponse.java
  src/main/resources/application.yml
  src/main/resources/security/.gitkeep
  src/test/java/com/mangojelly/backend/domain/member/MemberServiceTest.java
  src/test/java/com/mangojelly/backend/fixture/MemberFixture.java
Labels: 기능

#20 Feat/#5
  src/main/java/com/mangojelly/backend/applicatoin/controller/RoomController.java
  src/main/java/com/mangojelly/backend/applicatoin/dto/request/RoomCreateRequest.java
  src/main/java/com/mangojelly/backend/applicatoin/dto/response/RoomCreateResponse.java
  src/main/java/com/mangojelly/backend/applicatoin/facade/RoomFacade.java
  src/main/java/com/mangojelly/backend/domain/member/MemberRepository.java
  src/main/java/com/mangojelly/backend/domain/member/MemberService.java
  src/main/java/com/mangojelly/backend/domain/room/Room.java
  src/main/java/com/mangojelly/backend/domain/room/RoomMapper.java
  src/main/java/com/mangojelly/backend/domain/room/RoomRepository.java
  src/main/java/com/mangojelly/backend/domain/room/RoomService.java
  src/main/java/com/mangojelly/backend/global/config/WebConfig.java
  src/main/java/com/mangojelly/backend/global/error/ErrorCode.java
  src/main/java/com/mangojelly/backend/global/response/api/ResponseCode.java
  src/test/java/com/mangojelly/backend/domain/member/MemberServiceTest.java
  src/test/java/com/mangojelly/backend/domain/room/RoomServiceTest.java
  src/test/java/com/mangojelly/backend/fixture/RoomFixture.java
Labels: 기능

#21 Feat/#16
  build.gradle
  src/main/java/com/mangojelly/backend/applicatoin/facade/InitialFacade.java
  src/main/java/com/mangojelly/backend/applicatoin/runner/MangoJellyApplicationRunner.java
  src/main/java/com/mangojelly/backend/applicatoin/runner/vo/SceneVo.java
  src/main/java/com/mangojelly/backend/applicatoin/runner/vo/ScriptVo.java
  src/main/java/com/mangojelly/backend/applicatoin/runner/vo/ScriptWrapper.java
  src/main/java/com/mangojelly/backend/domain/role/RoleMapper.java
  src/main/java/com/mangojelly/backend/domain/role/RoleRepository.java
  src/main/java/com/mangojelly/backend/domain/role/RoleService.java
  src/main/java/com/mangojelly/backend/domain/scenario/Scenario.java
  src/main/java/com/mangojelly/backend/domain/scenario/ScenarioRepository.java
  src/main/java/com/mangojelly/backend/domain/scenario/ScenarioService.java
  src/main/java/com/mangojelly/backend/domain/scene/SceneMapper.java
  src/main/java/com/mangojelly/backend/domain/scene/SceneRepository.java
  src/main/java/com/mangojelly/backend/domain/scene/SceneService.java
  src/main/java/com/mangojelly/backend/domain/script/ScriptMapper.java
  src/main/java/com/mangojelly/backend/domain/script/ScriptRepository.java
  src/main/java/com/mangojelly/backend/domain/script/ScriptService.java
  src/main/java/com/mangojelly/backend/global/common/S3FileUploader.java
  src/main/java/com/mangojelly/backend/global/config/S3Config.java
  src/main/java/com/mangojelly/backend/global/error/ErrorCode.java
  src/main/resources/sample/Scripts.json
  src/main/resources/sample/image/sample/role/role1.png
  src/main/resources/sample/image/sample/role/role2.png
  src/main/resources/sample/image/sample/scene/sampleScene1.png
  src/main/resources/sample/image/sample/scene/sampleScene2.png
  src/main/resources/sample/image/sample/thumbnail.png
  src/test/java/com/mangojelly/backend/applicatoin/facade/InitialFacadeTest.java
  src/test/java/com/mangojelly/backend/domain/scenario/ScenarioServiceTest.java
  src/test/java/com/mangojelly/backend/global/common/S3FileUploaderTest.java
Labels: 기능

#28 Feat/#26
  src/main/java/com/mangojelly/backend/applicatoin/controller/MemberController.java
  src/main/java/com/mangojelly/backend/applicatoin/dto/request/GuestRequest.java
  src/main/java/com/mangojelly/backend/applicatoin/dto/request/GuestRoleRequest.java
  src/main/java/com/mangojelly/backend/applicatoin/dto/request/GuestSessionRequest.java
  src/main/java/com/mangojelly/backend/applicatoin/dto/response/GetAllGuestResponse.java
  src/main/java/com/mangojelly/backend/applicatoin/dto/response/GetGuestResponse.java
  src/main/java/com/mangojelly/backend/applicatoin/dto/response/GuestCreateResponse.java
  src/main/java/com/mangojelly/backend/applicatoin/facade/MemberFacade.java
  src/main/java/com/mangojelly/backend/domain/guest/Guest.java
  src/main/java/com/mangojelly/backend/domain/guest/GuestMapper.java
  src/main/java/com/mangojelly/backend/domain/guest/GuestRepository.java
  src/main/java/com/mangojelly/backend/domain/guest/GuestService.java
  src/main/java/com/mangojelly/backend/domain/member/MemberRepository.java
  src/main/java/com/mangojelly/backend/domain/role/RoleRepository.java
  src/main/java/com/mangojelly/backend/domain/role/RoleService.java
  src/main/java/com/mangojelly/backend/domain/room/RoomService.java
  src/main/java/com/mangojelly/backend/global/error/ErrorCode.java
  src/main/java/com/mangojelly/backend/global/response/api/ResponseCode.java
Labels: 기능, 리펙토링

#30 Feat/#23
  Dockerfile
  docker-compose.spring.yml
  gradlew
  src/main/java/com/mangojelly/backend/applicatoin/controller/MemberController.java
  src/main/java/com/mangojelly/backend/applicatoin/controller/MovieController.java
  src/main/java/com/mangojelly/backend/applicatoin/controller/ScriptController.java
  src/main/java/com/mangojelly/backend/applicatoin/dto/request/GuestRequest.java
  src/main/java/com/mangojelly/backend/applicatoin/dto/request/GuestRoleRequest.java
  src/main/java/com/mangojelly/backend/applicatoin/dto/request/GuestSessionRequest.java
  src/main/java/com/mangojelly/backend/applicatoin/dto/response/GetAllGuestResponse.java
  src/main/java/com/mangojelly/backend/applicatoin/dto/response/GetGuestResponse.java
  src/main/java/com/mangojelly/backend/applicatoin/dto/response/GuestCreateResponse.java
  src/main/java/com/mangojelly/backend/applicatoin/facade/MemberFacade.java
  src/main/java/com/mangojelly/backend/applicatoin/facade/ScriptFacade.java
  src/main/java/com/mangojelly/backend/domain/guest/Guest.java
  src/main/java/com/mangojelly/backend/domain/guest/GuestMapper.java
  src/main/java/com/mangojelly/backend/domain/guest/GuestRepository.java
  src/main/java/com/mangojelly/backend/domain/guest/GuestService.java
  src/main/java/com/mangojelly/backend/domain/role/RoleRepository.java
  src/main/java/com/mangojelly/backend/domain/role/RoleService.java
  src/main/java/com/mangojelly/backend/domain/room/RoomService.java
  src/main/java/com/mangojelly/backend/domain/script/ScriptRepository.java
  src/main/java/com/mangojelly/backend/domain/script/ScriptService.java
  src/main/java/com/mangojelly/backend/global/common/S3FileUploader.java
  src/main/java/com/mangojelly/backend/global/error/ErrorCode.java
  src/main/java/com/mangojelly/backend/global/error/ErrorCode.java.orig
  src/main/java/com/mangojelly/backend/global/response/api/ResponseCode.java
  src/test/java/com/mangojelly/backend/applicatoin/controller/MovieControllerTest.java
  src/test/java/com/mangojelly/backend/domain/Script/ScriptServiceTest.java
  src/test/java/com/mangojelly/backend/domain/room/RoomServiceTest.java
Labels: 기능

#33 Refact/#32
  src/main/java/com/mangojelly/backend/applicatoin/controller/MemberController.java
  src/main/java/com/mangojelly/backend/applicatoin/facade/MemberFacade.java
  src/main/java/com/mangojelly/backend/domain/authToken/AuthToken.java
  src/main/java/com/mangojelly/backend/domain/authToken/AuthTokenRepository.java
  src/main/java/com/mangojelly/backend/domain/authToken/AuthTokenService.java
  src/main/java/com/mangojelly/backend/domain/member/MemberRepository.java
  src/main/java/com/mangojelly/backend/domain/room/RoomService.java
  src/main/java/com/mangojelly/backend/global/response/api/ResponseCode.java
  src/test/java/com/mangojelly/backend/applicatoin/controller/MovieControllerTest.java
  src/test/java/com/mangojelly/backend/domain/room/RoomServiceTest.java
Labels: 리펙토링
